spring.application.name=silentsignals
server.port=8081
# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/silentsignals
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXP}

# Mail
spring.mail.host=smtp.ethereal.email
spring.mail.port=587
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true