spring.application.name=silentsignals

# PostgreSQL
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/silentsignals
spring.datasource.username=dev
spring.datasource.password=devpass
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# JWT
jwt.secret=mysupersecretkey

# Mail (optional)
spring.mail.host=smtp.ethereal.email
spring.mail.port=587
spring.mail.username=junius.collier@ethereal.email
spring.mail.password=qxDnqa7m7aVhqvZUvz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true